defmodule Onelist.Repo.Migrations.AddRolesAndWatchUsers do
  @moduledoc """
  Adds roles array to users table and creates watch users.

  PLAN-051: Phoenix Auth Migration
  - Adds roles field for role-based access control
  - Creates accounts for watch users (cynthia, devin, danielle, eq, mal, ari, mae, opey)
  - Grants "watch" role to all watch users including splntrb
  """
  use Ecto.Migration

  def up do
    # Add roles column to users table
    alter table(:users) do
      add :roles, {:array, :string}, default: [], null: false
    end

    # Create index for efficient role queries
    create index(:users, [:roles], using: "GIN")

    # Flush to ensure column exists before we insert data
    flush()

    # Add "watch" role to splntrb if they exist
    execute """
    UPDATE users
    SET roles = array_append(roles, 'watch')
    WHERE username = 'splntrb'
    AND NOT ('watch' = ANY(roles))
    """

    # Also add "admin" role to splntrb
    execute """
    UPDATE users
    SET roles = array_append(roles, 'admin')
    WHERE username = 'splntrb'
    AND NOT ('admin' = ANY(roles))
    """

    # Create watch users with placeholder emails
    # Using random passwords - users will reset via email or admin
    now = NaiveDateTime.utc_now() |> NaiveDateTime.truncate(:second)

    watch_users = [
      "cynthia",
      "devin",
      "danielle",
      "eq",
      "mal",
      "ari",
      "mae",
      "opey"
    ]

    for username <- watch_users do
      # Generate a random hashed password (they'll need to reset)
      # Using Bcrypt format placeholder - actual hash would be generated by app
      random_hash = "$2b$12$" <> Base.encode64(:crypto.strong_rand_bytes(22), padding: false)

      execute """
      INSERT INTO users (id, email, username, hashed_password, roles, email_verified, inserted_at, updated_at)
      VALUES (
        gen_random_uuid(),
        '#{username}@onelist.my',
        '#{username}',
        '#{random_hash}',
        ARRAY['watch'],
        true,
        '#{now}',
        '#{now}'
      )
      ON CONFLICT (email) DO UPDATE SET
        roles = array_append(
          array_remove(users.roles, 'watch'),
          'watch'
        )
      """
    end
  end

  def down do
    # Remove watch users
    execute """
    DELETE FROM users
    WHERE username IN ('cynthia', 'devin', 'danielle', 'eq', 'mal', 'ari', 'mae', 'opey')
    AND email LIKE '%@onelist.my'
    """

    # Remove roles from splntrb
    execute """
    UPDATE users
    SET roles = array_remove(array_remove(roles, 'watch'), 'admin')
    WHERE username = 'splntrb'
    """

    # Drop index
    drop index(:users, [:roles])

    # Remove roles column
    alter table(:users) do
      remove :roles
    end
  end
end
